### ISSUE TITLE
FastaFilenNames from fgcz_create_fasta.R

### ISSUE THREAD

**Issue by jjGG** [protViz/prozor#6]
Hoi Witold, 

Here so we dont forget the issue with the naming of the fasta file.
Ideally, the "_d_" for decoy is NOT added at the end of the "folder-name" but rather at the 3rd position:

e.g.:
`fgcz_create_fasta.R p3189_db1_AraNAvidin/ `
-> now results in: p3189_db1_AraNAvidin_d_20220503.fasta
-> I would prefer: p3189_db1_d_AraNAvidin_20220503.fasta

cheers- jonas

**Comment by wolski** [comment]
I think we all got used that the _d is after the database name.
